package com.inter.trade.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CREDIT_CARD_RECORD.
 */
public class CreditCardRecord {

    private Long id;
    private String user;
    private String creditcard;
    private String name;
    private String idcard;
    private String phone;

    public CreditCardRecord() {
    }

    public CreditCardRecord(Long id) {
        this.id = id;
    }

    public CreditCardRecord(Long id, String user, String creditcard, String name, String idcard, String phone) {
        this.id = id;
        this.user = user;
        this.creditcard = creditcard;
        this.name = name;
        this.idcard = idcard;
        this.phone = phone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getCreditcard() {
        return creditcard;
    }

    public void setCreditcard(String creditcard) {
        this.creditcard = creditcard;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIdcard() {
        return idcard;
    }

    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

}
