package com.inter.trade.db;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordDaoConfig;
    private final DaoConfig creditCardRecordDaoConfig;
    private final DaoConfig supportBankDaoConfig;

    private final RecordDao recordDao;
    private final CreditCardRecordDao creditCardRecordDao;
    private final SupportBankDao supportBankDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        creditCardRecordDaoConfig = daoConfigMap.get(CreditCardRecordDao.class).clone();
        creditCardRecordDaoConfig.initIdentityScope(type);

        supportBankDaoConfig = daoConfigMap.get(SupportBankDao.class).clone();
        supportBankDaoConfig.initIdentityScope(type);

        recordDao = new RecordDao(recordDaoConfig, this);
        creditCardRecordDao = new CreditCardRecordDao(creditCardRecordDaoConfig, this);
        supportBankDao = new SupportBankDao(supportBankDaoConfig, this);

        registerDao(Record.class, recordDao);
        registerDao(CreditCardRecord.class, creditCardRecordDao);
        registerDao(SupportBank.class, supportBankDao);
    }
    
    public void clear() {
        recordDaoConfig.getIdentityScope().clear();
        creditCardRecordDaoConfig.getIdentityScope().clear();
        supportBankDaoConfig.getIdentityScope().clear();
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

    public CreditCardRecordDao getCreditCardRecordDao() {
        return creditCardRecordDao;
    }

    public SupportBankDao getSupportBankDao() {
        return supportBankDao;
    }

}
