package com.inter.trade.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECORD.
 */
public class Record {

    private Long id;
    private Integer number;
    private Integer key;

    public Record() {
    }

    public Record(Long id) {
        this.id = id;
    }

    public Record(Long id, Integer number, Integer key) {
        this.id = id;
        this.number = number;
        this.key = key;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Integer getKey() {
        return key;
    }

    public void setKey(Integer key) {
        this.key = key;
    }

}
