package com.inter.trade.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUPPORT_BANK.
 */
public class SupportBank {

    private Long id;
    private String bankid;
    private String bankno;
    private String bankname;

    public SupportBank() {
    }

    public SupportBank(Long id) {
        this.id = id;
    }

    public SupportBank(Long id, String bankid, String bankno, String bankname) {
        this.id = id;
        this.bankid = bankid;
        this.bankno = bankno;
        this.bankname = bankname;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBankid() {
        return bankid;
    }

    public void setBankid(String bankid) {
        this.bankid = bankid;
    }

    public String getBankno() {
        return bankno;
    }

    public void setBankno(String bankno) {
        this.bankno = bankno;
    }

    public String getBankname() {
        return bankname;
    }

    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

}
